version: "3"

services:
  insightbeam-server:
    build: .
    ports: 
    - "8000:8000"
    volumes:
      - type: bind
        source: ./data/server
        target: /home/insightbeam-runner/service/data
